### ISSUE TITLE
README Instructions Filenames

### ISSUE THREAD

**Issue by joserodrigorojo** [martinshkreli/13F#1]
The filename in these 2 lines doesn't match the script in the repo:

https://github.com/martinshkreli/13F/blob/5ee77142c6df43bcaf3a05a93d25a3b0a7988c55/README.md?plain=1#L24
https://github.com/martinshkreli/13F/blob/5ee77142c6df43bcaf3a05a93d25a3b0a7988c55/README.md?plain=1#L33

**Comment by martinshkreli** [comment]
thats cause its an example!
